dubbo:
  application:
    name: ns-consumer
  protocol:
    name: dubbo
    port: -1
  registry:
    id: zk-registry
    address: 127.0.0.1:2181
    protocol: zookeeper
  config-center:
    address: zookeeper://127.0.0.1:2181
  metadata-report:
    address: zookeeper://127.0.0.1:2181

server:
  port: 8003